#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Hucky::Starting pre-commnit hook"
echo "Hucky::Running type check"

yarn type:check

echo "Hucky::Running ESlint"

yarn lint

echo "Hucky::Running Tests"

yarn tests

npx --no -- commitlint --edit "$1"


